apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    apps: mypod
spec:
  containers:
    - name: mypod
      image: ubuntu
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - name: myconfig
        mountPath: "/etc/myconfig"
        readOnly: true
  volumes:
    - name: myconfig
      configMap:
      name: myconfig

